name: TradeSystem
author: CodingAir
version: "1.1.13"
description: A beautiful way to trade with other players.
main: de.codingair.tradesystem.TradeSystem
softdepend: [Vault, Essentials, PlaceholderAPI]
api-version: "1.13"