name: TradeSystem
author: CodingAir
version: 1.0.5
description: TradeSystem by CodingAir
main: de.codingair.tradesystem.TradeSystem
softdepend: [Vault, Essentials]
api-version: 1.13

commands:
  trade:
    usuage: /trade <Player, Accept, Deny>
    description: Trade-System-CMD
  tradesystem:
    usuage: /tradesystem
    description: Trade-System-CMD
    aliases: [ts]