name: TradeSystem
author: CodingAir
version: "1.1.10"
description: A beautiful way to trade with other players.
main: de.codingair.tradesystem.TradeSystem
softdepend: [Vault, Essentials]
api-version: "1.13"