name: Build-Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and deploy
        run: |
          mvn -B package --file pom.xml
          file=$(find target -type f -name "TradeSystem_v*.jar" | head -n 1)
          name=${file[@]//.jar/}
          name=${name:7}
          info=${name##*_}
          version=${name:12}
          version=${version[@]//_$info/}
          if [ "$info" = "$version" ]; then
          	info="New release**__   -   __**"
          else
          	info=${info[@]//-/ }
          	info="$info**__   -   __**"
          fi
          NOW="$(LC_ALL=en_GB.utf8 date --universal) $(LC_ALL=en_GB.utf8 date --universal '+%p %Z')"
          milestone=15
          hook=${{ secrets.DISCORD_WEBHOOK }}
          echo "Sending '$file' to 'DevBuilds' channel, this may take a while..."
          curl -i -H 'Expect: application/json' -F file=@"$file" -F "payload_json={ \"wait\": true, \"avatar_url\":\"https://i.imgur.com/x3pSH55.png\", \"content\": \"@here\n__**$info$version**__   [$NOW]\n\n**Changelog:**\n<https://github.com/CodingAir/TradeSystem/milestone/$milestone?closed=1>\", \"username\": \"TradeSystem CI\" }" $hook
